### get all credentials
GET http://localhost:3000/api/credentials

### get one credential
GET http://localhost:3000/api/credentials/google

### post credential
POST http://localhost:3000/api/credentials
Content-Type: application/json

{
    "service": "mySpace",
    "username": "Fosy",
    "passwords": "123"
}

### delete credential
DELETE http://localhost:3000/api/credentials/mySpace

### update credential
PUT http://localhost:3000/api/credentials/mySpace
Content-Type: application/json

{
    "service": "mySpace",
    "username": "Fosy",
    "passwords": "123"
}