### get all credentials
GET http://localhost:3001/api/credentials
Authorization: {{$dotenv MASTERPASSWORD}}

### get one credential without authorization
GET http://localhost:3001/api/credentials/mySpace

### get one credential with wrong authorization
GET http://localhost:3001/api/credentials/mySpace
Authorization: nope

### post credential
POST http://localhost:3001/api/credentials
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "Google",
    "username": "Fosy",
    "password": "123"
}

### post new credential
POST http://localhost:3001/api/credentials
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "twitter",
    "username": "Fosy",
    "password": "123"
}

### delete credential
DELETE http://localhost:3001/api/credentials/mySpace

### update credential
PUT http://localhost:3001/api/credentials/mySpace
Content-Type: application/json
Authorization: {{$dotenv MASTERPASSWORD}}

{
    "service": "mySpace",
    "username": "Fosy",
    "password": "123456"
}

### get single credential

GET http://localhost:3001/api/credentials/mySpace
Authorization: {{$dotenv MASTERPASSWORD}}